#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yodai Shiota shioyan0809@icloud.com
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0
denominator = 0
avarage = 0

for line in sys.stdin:
    denominator += 1
    try:
         ans += int(line)
    except:
         ans += float(line)

avarage = ans / denominator
print(ans)
print(avarage)
