#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Yodai Shiota shioyan0809@icloud.com
import sys

ans = 0
for line in sys.stdin:
    try:
         ans += int(line)
    except:
         ans += float(line)

print(ans)
